# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pivotal_doc}
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Linquist"]
  s.date = %q{2011-02-28}
  s.description = %q{
        Automated release notes for apps hosted on pivotaltracker.com.  
        Allows release notes to be generated for any project on pivotaltracker.com by retrieving the latest iteration for the specified project and displaying the completed features, bugs, and chores.
      }
  s.email = %q{tim.linquist@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "VERSION",
    "assets/css/ui-lightness/images/ui-bg_diagonals-thick_18_b81900_40x40.png",
    "assets/css/ui-lightness/images/ui-bg_diagonals-thick_20_666666_40x40.png",
    "assets/css/ui-lightness/images/ui-bg_flat_10_000000_40x100.png",
    "assets/css/ui-lightness/images/ui-bg_glass_100_f6f6f6_1x400.png",
    "assets/css/ui-lightness/images/ui-bg_glass_100_fdf5ce_1x400.png",
    "assets/css/ui-lightness/images/ui-bg_glass_65_ffffff_1x400.png",
    "assets/css/ui-lightness/images/ui-bg_gloss-wave_35_f6a828_500x100.png",
    "assets/css/ui-lightness/images/ui-bg_highlight-soft_100_eeeeee_1x100.png",
    "assets/css/ui-lightness/images/ui-bg_highlight-soft_75_ffe45c_1x100.png",
    "assets/css/ui-lightness/images/ui-icons_222222_256x240.png",
    "assets/css/ui-lightness/images/ui-icons_228ef1_256x240.png",
    "assets/css/ui-lightness/images/ui-icons_ef8c08_256x240.png",
    "assets/css/ui-lightness/images/ui-icons_ffd27a_256x240.png",
    "assets/css/ui-lightness/images/ui-icons_ffffff_256x240.png",
    "assets/css/ui-lightness/jquery-ui-1.8.5.custom.css",
    "assets/js/jquery-1.4.2.min.js",
    "assets/js/jquery-ui-1.8.5.custom.min.js",
    "lib/pivotal_doc.rb",
    "lib/pivotal_doc/configuration.rb",
    "lib/pivotal_doc/exceptions.rb",
    "lib/pivotal_doc/ext/date.rb",
    "lib/pivotal_doc/generator.rb",
    "lib/pivotal_doc/generators/base.rb",
    "lib/pivotal_doc/generators/csv.rb",
    "lib/pivotal_doc/generators/html.rb",
    "lib/pivotal_doc/generators/sprint.rb",
    "lib/pivotal_doc/release.rb",
    "lib/pivotal_doc/sprint.rb",
    "lib/pivotal_doc/work.rb",
    "pivotal_doc.gemspec",
    "spec/fixtures/configs.yml",
    "spec/fixtures/iterations.yml",
    "spec/fixtures/projects.yml",
    "spec/fixtures/stories.yml",
    "spec/lib/configuration_spec.rb",
    "spec/lib/ext/date_spec.rb",
    "spec/lib/generator_spec.rb",
    "spec/lib/generators/base_spec.rb",
    "spec/lib/generators/csv_spec.rb",
    "spec/lib/generators/html_spec.rb",
    "spec/lib/generators/sprint_spec.rb",
    "spec/lib/release_spec.rb",
    "spec/lib/sprint_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/support/mocks_helper.rb",
    "spec/support/pt_api_helpers.rb",
    "templates/fancy.haml",
    "templates/output.csv",
    "templates/output.haml",
    "templates/sprint.haml"
  ]
  s.homepage = %q{http://github.com/timo3377/pivotal_doc}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.3}
  s.summary = %q{A release documentation generator for pivotaltracker.com}
  s.test_files = [
    "spec/lib/configuration_spec.rb",
    "spec/lib/ext/date_spec.rb",
    "spec/lib/generator_spec.rb",
    "spec/lib/generators/base_spec.rb",
    "spec/lib/generators/csv_spec.rb",
    "spec/lib/generators/html_spec.rb",
    "spec/lib/generators/sprint_spec.rb",
    "spec/lib/release_spec.rb",
    "spec/lib/sprint_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/mocks_helper.rb",
    "spec/support/pt_api_helpers.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<pivotal-tracker>, [">= 0"])
      s.add_development_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<factory_girl>, ["= 1.3.2"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_runtime_dependency(%q<pivotal-tracker>, [">= 0.2.1"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<fastercsv>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<pivotal-tracker>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<factory_girl>, ["= 1.3.2"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<pivotal-tracker>, [">= 0.2.1"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<pivotal-tracker>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<factory_girl>, ["= 1.3.2"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<pivotal-tracker>, [">= 0.2.1"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

